In [ ]:
%tensorflow_version 2.0.0
import tensorflow as tf
from tensorflow.keras import Sequential,Model
from tensorflow.keras.layers import Dense,Dropout,Flatten,BatchNormalization
from tensorflow.keras.applications.vgg16 import VGG16,preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!uname - ar

uname: extra operand ‘-’
Try 'uname --help' for more information.


In [ ]:
cd /content/drive/MyDrive

/content/drive/MyDrive


In [ ]:
!unzip Datasets

Archive:  Datasets.zip
   creating: Datasets/
   creating: Datasets/Test/
   creating: Datasets/Test/audi/
  inflating: Datasets/Test/audi/21.jpg  
  inflating: Datasets/Test/audi/22.jpg  
  inflating: Datasets/Test/audi/23.jpg  
  inflating: Datasets/Test/audi/24.jpg  
  inflating: Datasets/Test/audi/25.jpg  
  inflating: Datasets/Test/audi/26.jpg  
  inflating: Datasets/Test/audi/27.jpg  
 extracting: Datasets/Test/audi/28.jpg  
  inflating: Datasets/Test/audi/29.jpg  
   creating: Datasets/Test/lamborghini/
  inflating: Datasets/Test/lamborghini/1.jpg  
  inflating: Datasets/Test/lamborghini/10.jpg  
  inflating: Datasets/Test/lamborghini/11.jpg  
  inflating: Datasets/Test/lamborghini/12.jpg  
  inflating: Datasets/Test/lamborghini/13.jpg  
  inflating: Datasets/Test/lamborghini/14.jpg  
  inflating: Datasets/Test/lamborghini/15.jpg  
  inflating: Datasets/Test/lamborghini/16.jpg  
  inflating: Datasets/Test/lamborghini/17.jpg  
  inflating: Datasets/Test/lamborghini/18.jpg  
  inf

In [ ]:
# Importing the Keras libraries and packages
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras import losses
from tensorflow.keras import optimizers
from tensorflow.keras import metrics
# Initialising the CNN
classifier = Sequential()
# Step 1 - Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))
# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))
# Step 3 - Flattening
classifier.add(Flatten())
# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
classifier.add(Dense(units = 3, activation = 'softmax'))
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 62, 62, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 31, 31, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 29, 29, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 14, 14, 32)        0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 6272)              0         
                                                                 
 dense (Dense)               (None, 128)               8

In [ ]:
# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
#categorical_crossentropy
#https://keras.io/api/losses/probabilistic_losses/#categoricalcrossentropy-class

#classifier.compile(optimizer = 'sgd',loss = 'mean_squared_error', metrics = [metrics.categorical_accuracy])

In [ ]:
# Part 2 - Fitting the CNN to the images
from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
shear_range = 0.2,
zoom_range = 0.2,
horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)
#/content/drive/MyDrive/Datasets/Train
ph_training_set = train_datagen.flow_from_directory('/content/drive/MyDrive/Datasets/Train',
target_size = (64, 64),
batch_size = 32,
class_mode = 'categorical')

ph_test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/Datasets/Test',
target_size = (64, 64),
batch_size = 32,
class_mode = 'categorical')

#https://towardsdatascience.com/convolutional-neural-network-feature-map-and-filter-visualization-f75012a5a49c

Found 64 images belonging to 3 classes.
Found 58 images belonging to 3 classes.


In [ ]:
# fit the model
# Run the cell. It will take some time to execute
r = classifier.fit_generator(
  ph_training_set,
  validation_data=ph_test_set,
  epochs=50,
  steps_per_epoch=len(ph_training_set),
  validation_steps=len(ph_test_set)
)

<ipython-input-9-be2bf5cac9c5>:3: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  r = classifier.fit_generator(


Epoch 1/50
2/2 [==============================] - 3s 1s/step - loss: 1.3007 - accuracy: 0.3906 - val_loss: 1.4122 - val_accuracy: 0.3103
Epoch 2/50
2/2 [==============================] - 2s 998ms/step - loss: 1.1174 - accuracy: 0.4844 - val_loss: 1.3032 - val_accuracy: 0.1724
Epoch 3/50
2/2 [==============================] - 3s 2s/step - loss: 1.0762 - accuracy: 0.4375 - val_loss: 1.0665 - val_accuracy: 0.4655
Epoch 4/50
2/2 [==============================] - 1s 889ms/step - loss: 1.0268 - accuracy: 0.5781 - val_loss: 1.0134 - val_accuracy: 0.6034
Epoch 5/50
2/2 [==============================] - 1s 908ms/step - loss: 1.0110 - accuracy: 0.5312 - val_loss: 1.0106 - val_accuracy: 0.6034
Epoch 6/50
2/2 [==============================] - 1s 911ms/step - loss: 0.9585 - accuracy: 0.5938 - val_loss: 1.0099 - val_accuracy: 0.5517
Epoch 7/50
2/2 [==============================] - 1s 836ms/step - loss: 0.9220 - accuracy: 0.6094 - val_loss: 1.0531 - val_accuracy: 0.4483
Epoch 8/50
2/2 [==========

In [ ]:
from tensorflow.keras.models import load_model

classifier.save('Model_Cars-identification-04-03-2024.h5')

In [ ]:
# Second Part-2

In [ ]:
!wget https://computer-vision-2022.s3.ap-south-1.amazonaws.com/Model_Cars-identification-06-10-2021.h5

--2023-11-20 14:29:55--  https://computer-vision-2022.s3.ap-south-1.amazonaws.com/Model_Cars-identification-06-10-2021.h5
Resolving computer-vision-2022.s3.ap-south-1.amazonaws.com (computer-vision-2022.s3.ap-south-1.amazonaws.com)... 3.5.212.121, 52.219.64.99, 52.219.156.174, ...
Connecting to computer-vision-2022.s3.ap-south-1.amazonaws.com (computer-vision-2022.s3.ap-south-1.amazonaws.com)|3.5.212.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9807272 (9.4M) [binary/octet-stream]
Saving to: ‘Model_Cars-identification-06-10-2021.h5’

Model_Cars-identifi 100%[===================>]   9.35M  4.07MB/s    in 2.3s    

2023-11-20 14:29:58 (4.07 MB/s) - ‘Model_Cars-identification-06-10-2021.h5’ saved [9807272/9807272]



In [ ]:
!pwd

/content/drive/MyDrive


In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [ ]:
model=load_model('/content/drive/MyDrive/Model_Cars-identification-04-03-2024.h5')

In [ ]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('/content/audi.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(result)
#Audi -1

1/1 [==============================] - 0s 122ms/step
[[1. 0. 0.]]


In [ ]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('/content/lam.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(result)
#Lam-010

1/1 [==============================] - 0s 26ms/step
[[0. 1. 0.]]


In [ ]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('/content/mer.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(result)
#mer-001

1/1 [==============================] - 0s 25ms/step
[[0. 0. 1.]]


In [ ]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('/content/audi1.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)
print(result)
#Audi-100

1/1 [==============================] - 0s 26ms/step
[[1. 0. 0.]]
